apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-pvc
  labels:
    app: mysql-app 

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi